server.port=${PORT:8080}

spring.application.name=electronics-store

# ================= DATABASE =================
# Railway / Cloud s? inject DATABASE_URL
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# ================= JPA / HIBERNATE =================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ================= JWT =================
# Access Token
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=900000

# Refresh Token
jwt.refresh-secret=6A576E5A7234753778214125442A472D4B6150645367566B5970337336763979
jwt.refresh-expiration=2592000000
